platform :ios, "8.0"
target '彩票' do
  pod 'AFNetworking', '3.1.0'
  pod 'MJRefresh', '~> 3.1.12'
  pod 'SDWebImage', '~> 4.0.0'
  pod 'ODRefreshControl', '1.2'
  pod 'NJKWebViewProgress', '0.2.3'
  pod 'BmobSDK'
  pod 'SVProgressHUD'
  pod 'JSONModel','~>1.1'
  pod 'PureLayout'#,'2.0.6'
  pod 'BlocksKit'#,'2.2.5'
  pod 'UIView+FDCollapsibleConstraints'
  pod 'ChameleonFramework', '~> 2.1.0'
  pod 'SDCycleScrollView', '~> 1.66'
  pod 'Masonry', '1.0.0'
  pod 'NYSegmentedControl', '~> 1.1.0'
  pod 'WMPageController'
  pod 'ARSegmentPager', '~> 1.1.2'
  pod 'ReactiveCocoa', '2.5'
  pod 'HSSetTableViewController', '~> 1.1.3'
  pod 'PNChart', '~> 0.8.9'
  pod 'Meiqia', '~> 3.3.4.1'
end

